In [1]:
#Importing several libraries to play with the data
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
import matplotlib.pyplot as plt
%matplotlib inline

#Reading the csv file
df = pd.read_csv("/content/drive/MyDrive/datasets/CarPrice_Assignment.csv")

In [2]:
#Printing the data summary
print(" Data Summary\n \n ", df.isnull().sum())

 Data Summary
 
  car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64


In [3]:
#Printing some data from the end
df.tail(10)

car_ID  symboling          CarName  ... citympg highwaympg    price
195     196         -1      volvo 144ea  ...      23         28  13415.0
196     197         -2      volvo 244dl  ...      24         28  15985.0
197     198         -1        volvo 245  ...      24         28  16515.0
198     199         -2      volvo 264gl  ...      17         22  18420.0
199     200         -1     volvo diesel  ...      17         22  18950.0
200     201         -1  volvo 145e (sw)  ...      23         28  16845.0
201     202         -1      volvo 144ea  ...      19         25  19045.0
202     203         -1      volvo 244dl  ...      18         23  21485.0
203     204         -1        volvo 246  ...      26         27  22470.0
204     205         -1      volvo 264gl  ...      19         25  22625.0

[10 rows x 26 columns]

In [4]:
#Filling the missing values in the dataset
df = df.fillna(method='bfill')
df = df.fillna(method='ffill')

In [5]:
#Checking for null values
print("Data Summary\n \n ", df.isnull().sum())

Data Summary
 
  car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64


In [6]:
df.head(20)

car_ID  symboling                   CarName  ... citympg highwaympg      price
0        1          3        alfa-romero giulia  ...      21         27  13495.000
1        2          3       alfa-romero stelvio  ...      21         27  16500.000
2        3          1  alfa-romero Quadrifoglio  ...      19         26  16500.000
3        4          2               audi 100 ls  ...      24         30  13950.000
4        5          2                audi 100ls  ...      18         22  17450.000
5        6          2                  audi fox  ...      19         25  15250.000
6        7          1                audi 100ls  ...      19         25  17710.000
7        8          1                 audi 5000  ...      19         25  18920.000
8        9          1                 audi 4000  ...      17         20  23875.000
9       10          0       audi 5000s (diesel)  ...      16         22  17859.167
10      11          2                  bmw 320i  ...      23         29  16430.000
11      12          0                  bmw 320i  ...      23         29  16925.000
12      13          0                    bmw x1  ...      21         28  20970.000
13      14          0                    bmw x3  ...      21         28  21105.000
14      15          1                    bmw z4  ...      20         25  24565.000
15      16          0                    bmw x4  ...      16         22  30760.000
16      17          0                    bmw x5  ...      16         22  41315.000
17      18          0                    bmw x3  ...      15         20  36880.000
18      19          2          chevrolet impala  ...      47         53   5151.000
19      20          1     chevrolet monte carlo  ...      38         43   6295.000

[20 rows x 26 columns]

In [3]:
#Importing the patsy library for data transformation 
import patsy
from patsy import dmatrices, dmatrix

In [4]:
#Performing dmatrices on the column horsepower and citympg
y,X = dmatrices('horsepower ~ citympg', data = df)

In [9]:
#Defining the type of y
type(y)

patsy.design_info.DesignMatrix

In [10]:
#Defining the type of x
type(X)

patsy.design_info.DesignMatrix

In [11]:
#Printing the number of values
X.shape

(205, 2)

In [12]:
#Printing transformed values
X[:5]

array([[ 1., 21.],
       [ 1., 21.],
       [ 1., 19.],
       [ 1., 24.],
       [ 1., 18.]])

In [5]:
#Printing the number of values
y.shape

(205, 1)

In [14]:
#Printing transformed values
y[:5]

array([[111.],
       [111.],
       [154.],
       [102.],
       [115.]])

In [15]:
#Defining a formula where we are taking out the sum between the lileage valur of the city and on the highway
y,X = dmatrices('horsepower ~ citympg+highwaympg', data = df)

In [16]:
y,X = dmatrices('horsepower ~ citympg+highwaympg -1', data = df)

In [17]:
X = dmatrix('citympg+highwaympg', data= df)

In [18]:
X = dmatrix('citympg+highwaympg', data= df)

In [19]:
#Performing a calculation on the data
X = dmatrix('I(citympg*2) + highwaympg', data= df)

In [20]:
#Printing transformed values
X[:5]

array([[ 1., 42., 27.],
       [ 1., 42., 27.],
       [ 1., 38., 26.],
       [ 1., 48., 30.],
       [ 1., 36., 22.]])

In [21]:
X = dmatrix('standardize(citympg)+highwaympg', data=df)

In [22]:
#Printing transformed values
X[:5]

array([[ 1.        , -0.64655303, 27.        ],
       [ 1.        , -0.64655303, 27.        ],
       [ 1.        , -0.95301169, 26.        ],
       [ 1.        , -0.18686504, 30.        ],
       [ 1.        , -1.10624102, 22.        ]])

In [23]:
#Implementing a function called mileage
def mileage(miles):
  return miles *5

In [24]:
X = dmatrix('citympg + highwaympg + mileage(price)', data = df)

In [25]:
df.fueltype.dtype

dtype('O')

In [26]:
df.fueltype.unique()

array(['gas', 'diesel'], dtype=object)

In [27]:
df.CarName.unique()

array(['alfa-romero giulia', 'alfa-romero stelvio',
       'alfa-romero Quadrifoglio', 'audi 100 ls', 'audi 100ls',
       'audi fox', 'audi 5000', 'audi 4000', 'audi 5000s (diesel)',
       'bmw 320i', 'bmw x1', 'bmw x3', 'bmw z4', 'bmw x4', 'bmw x5',
       'chevrolet impala', 'chevrolet monte carlo', 'chevrolet vega 2300',
       'dodge rampage', 'dodge challenger se', 'dodge d200',
       'dodge monaco (sw)', 'dodge colt hardtop', 'dodge colt (sw)',
       'dodge coronet custom', 'dodge dart custom',
       'dodge coronet custom (sw)', 'honda civic', 'honda civic cvcc',
       'honda accord cvcc', 'honda accord lx', 'honda civic 1500 gl',
       'honda accord', 'honda civic 1300', 'honda prelude',
       'honda civic (auto)', 'isuzu MU-X', 'isuzu D-Max ',
       'isuzu D-Max V-Cross', 'jaguar xj', 'jaguar xf', 'jaguar xk',
       'maxda rx3', 'maxda glc deluxe', 'mazda rx2 coupe', 'mazda rx-4',
       'mazda glc deluxe', 'mazda 626', 'mazda glc', 'mazda rx-7 gs',
       'mazda glc 

In [28]:
df.carbody.unique()

array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object)

In [29]:
X = dmatrix('C(carbody)+citympg-1', data = df)

In [30]:
#Printing transformed values
X[:5]

array([[ 1.,  0.,  0.,  0.,  0., 21.],
       [ 1.,  0.,  0.,  0.,  0., 21.],
       [ 0.,  0.,  1.,  0.,  0., 19.],
       [ 0.,  0.,  0.,  1.,  0., 24.],
       [ 0.,  0.,  0.,  1.,  0., 18.]])